name: Build/Release
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install

      - name: Build and Release
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LotteryManager-Windows
          path: release/*.exe
